# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 13:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.TextField(db_index=True, unique=True)),
                ('video_ids', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('words_count', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.TextField(db_index=True, unique=True)),
                ('subtitle_original', models.TextField(blank=True, null=True)),
                ('subtitle_original_formatted', models.TextField(blank=True, null=True)),
                ('subtitle_original_lang', models.TextField(blank=True, null=True)),
                ('subtitle_translated', models.TextField(blank=True, null=True)),
                ('subtitle_translated_formatted', models.TextField(blank=True, null=True)),
                ('words_count', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
